// src/App.tsx
import * as React from "react"
import {
  ChakraProvider,
  Button,
  Container,
  Skeleton,
  useBoolean,
  useDisclosure,
  Box,
  ModalOverlay,
} from "@chakra-ui/react"

import theme from "./theme"
import { NavBar } from "./NavBar";
import { ChallengesDrawer } from "./ChallengesDrawer";

import { Allotment } from "allotment";
import { EditorBox } from "./EditorBox";
import { LogBox } from "./LogBox";
import { DataFrame } from "./DataFrame";
import { Octokit } from "octokit"

import { TextFrame } from "./TextFrame";


import "allotment/dist/style.css";

import {ChallengeFile, Challenge} from "./interfaces"
import { ViewFrame } from "./ViewFrame";
import {WinDialog} from "./WinDialog"

declare const window: any;
let global_stdout:string = "";
let current_input: [] = []
let current_expected: [] = []


export function App()
{
  
  // function load challenges
  async function load_challenges() {
    
    const octokit = new Octokit()
    const data = await octokit.request('GET /repos/dridk/pandas-ninja/contents/challenges')
    let challenges = data["data"].map((el:ChallengeFile)=>{
      
      return {
        name: el["name"], 
        download_url: el["download_url"]
      }
    })
    return challenges
  }
  
  // function load challenge
  async function open_challenge(url:string){
    console.debug("open challenge")
    console.debug(url)
    let response = await fetch(url);
    response.json().then((el:Challenge)=>{
    
      current_input = el.input;
      current_expected = el.expected
      setCurrentChallenge(el) 

      setCode(`# Change the current \`df\` dataframe\n# to make it as the same as expected\ndf`)
      run_code()
      

  })
  }

  // append stdout 
  function append_stdout(text:string)
  {
    global_stdout = global_stdout + "\n" + text
    console.debug(global_stdout)
    setStdout(global_stdout)
  }


  // function load Python 
  async function load_python(){

    console.debug("Chargement de Python")
    setLoading(true)

    window.pyodide = await window.loadPyodide({
      stdout: (text:string) => append_stdout(text),
      stderr: (text:string)=> setStdErr(text )

    });
    console.log(window.pyodide.runPython(`
        import sys
        sys.version

    `));

    await window.pyodide.loadPackage(["pandas"]);
    console.log(window.pyodide.runPython(`
        import pandas as pd 
    `));
    setLoading(false)

    return true
  }

  // Check victory 
  
  function check_victory(user:any, expected:any){

    if (JSON.stringify(user) == JSON.stringify(expected))
    {
     console.debug("WIN !!!!!!!!!!")
      winDialog.onOpen()

    }

  }
 

   // Run python code
  function run_code(){

    
    setStdErr("")
    setTabIndex(0)

    console.debug(code)

    try {
    
    let input:[] = current_input


    window.pyodide.globals.set("raw_input", input)

       
    const start_code = `import js\nimport ast\ndf = pd.DataFrame(raw_input.to_py())`
    const end_code = `df = df.to_dict(orient="records")`
    const intro_code = `line_number=len(ast.parse("""${code}""").body)`

    let all_code = start_code + "\n" + code + "\n" + end_code + "\n" +intro_code


    window.pyodide.runPython(all_code);

    console.debug(intro_code)

    let json_result = window.pyodide.globals.get("df")
    let line_number = window.pyodide.globals.get("line_number")
    json_result = json_result.toJs({dict_converter : Object.fromEntries})
    
    console.debug(line_number)
   
    // setComputedData(json_result)

    // console.debug("=====A")
    // console.debug(window.json_result)
    


   

    // check_victory(json_result, current_expected)



 
   

    }

    catch (err)
    {
      let message = ((err as Error).message);
      console.debug(message)
      setStdErr(message)
      setTabIndex(1)
    }


   }
  
  
  
  
  
  // Keep Dark always
  React.useEffect(() => { localStorage.removeItem("chakra-ui-color-mode"); }, []);
  


  // State variable 
  const  drawerFlag = useDisclosure()
  const [challengeFiles, setChallengeFiles] = React.useState<ChallengeFile[]>([])
  const [currentChallenge, setCurrentChallenge] = React.useState<Challenge>()
  const [loading, setLoading] = React.useState<boolean>(true)

  const [computedData, setComputedData] = React.useState([])

  const [code, setCode] = React.useState<string>("");
  const [stdout, setStdout] = React.useState<string>();
  const [stderr, setStdErr] = React.useState<string>();
  const [tabIndex, setTabIndex] = React.useState<number>(0);

  const winDialog = useDisclosure({defaultIsOpen:false})

  // init application 
  React.useEffect(()=> {
    
    // Chargement de Python 
    load_python().then((e)=>{console.debug("Success")})

    // Load menu 
    load_challenges().then((files)=>setChallengeFiles(files))

    console.debug("salut\nboby")

    
    
  }, [])

  
  
  
  return (
    <ChakraProvider theme={theme} >

    <WinDialog isOpen={winDialog.isOpen} onClose={winDialog.onClose}/>

    <NavBar 
    title={currentChallenge?.name ?? "Not Set"} 
    description={currentChallenge?.description ?? ""}
    onDrawerClicked={drawerFlag.onOpen} 
    loading = {loading} />
    
    <ChallengesDrawer
    isOpen={drawerFlag.isOpen} 
    onClose={drawerFlag.onClose}
    challenges={challengeFiles}
    openChallenge={open_challenge}
    />
    
    
    <Box  height="92vh">
    
    <Allotment>
    <Allotment vertical={true}>
    
    <EditorBox 
    code={code}
    onCodeChanged={setCode}
    onRun={()=>run_code()} 
    
    />
    <LogBox stderr={stderr} stdout={stdout} index={tabIndex} onIndexChanged={setTabIndex}/>
    </Allotment>
    
    <Allotment vertical={true}>
   
    <ViewFrame title="yours" data={computedData}/>
    <ViewFrame title="expected" data={currentChallenge?.expected}/>
    
    {/* <DataFrame title="Input table" data={computedData}/> */}
    {/* <DataFrame title="Expected table"  data={currentChallenge?.expected ?? []}/> */}
    </Allotment>
    
    </Allotment>
    
    </Box>
    </ChakraProvider>
    )
    
  }

// src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import Header from "./Header.svelte";
  import ToolBar from "./ToolBar.svelte";
  import DataFrame from "./DataFrame.svelte";
  import LogBox from "./LogBox.svelte";
  import Badge from "./Badge.svelte";

  import CodeEditor from "./CodeEditor.svelte";
  import YouWin from "./YouWin.svelte";
  import Grid from "./Grid.svelte";
  import Console from "./Console.svelte";
  import ChallengeList from "./ChallengeList.svelte";
  import Loading from "./Loading.svelte";

  /** ======================
   *      Interface
   *========================
   */

  // Challenge List Item
  interface ChallengeListItem {
    title: string;
    file: string;
    level: string;
    age: string;
  }

  // Challenge object
  interface Challenge {
    title: string;
    author: string;
    placeholder?: string;
    input: Array<Object>;
    expected: Array<Object>;
  }

  /** ======================
   *      Variables
   *========================
   */

  let challengeList: ChallengeListItem[] = [];
  let challengeListIndex: number;
  let currentChallenge: Challenge;

  $: current_title = getChallengeListItem(challengeListIndex)?.title;
  $: current_level = getChallengeListItem(challengeListIndex)?.level;
  $: current_file = getChallengeListItem(challengeListIndex)?.file;
  $: challengeListIndex && loadChallenge(challengeListIndex);

  let pyodide: any = null;
  let loading: boolean = true;
  let consoleOutput: string;
  let code: string;
  let won: boolean = false;
  let score: number = 0;

  let computed_input: any = [];
  let computed_input_str: any = [];

  /** ======================
   *      Functions
   *========================
   */

  // Append text to console
  function appendConsole(text: string): void {
    consoleOutput = consoleOutput + "\n" + text;
  }

  // Clear console
  function clearConsole() {
    consoleOutput = "";
  }

  // Load challenges list
  async function loadChallengeList() {
    console.log("Load challenges List ");

    let response = await fetch("challenges.json");
    let el = await response.json();

    challengeList = el["data"];
    challengeListIndex = 0;

    await loadChallenge(challengeListIndex);

    return challengeList;
  }

  async function loadChallenge(index: number) {
    console.log(index, challengeList);
    let file = getChallengeListItem(index)?.file;

    console.debug(index, file, challengeList);

    let response = await fetch(`challenges/${file}`);

    let el: Challenge = await response.json();

    currentChallenge = el;
    code = currentChallenge.placeholder || "";

    runCode();
  }

  // Get a challengeListItem from index
  function getChallengeListItem(index: number): ChallengeListItem {
    if (index < challengeList.length) {
      return challengeList[index];
    }
    return undefined;
  }

  // Load Python
  async function loadPython() {
    loading = true;
    pyodide = await loadPyodide({
      stdout: (text: string) => appendConsole(text),
      stderr: (text: string) => appendConsole(text),
    });
    // Pyodide is now ready to use...
    console.log(
      pyodide.runPython(`
      import sys
      sys.version
      `)
    );

    // Load Pandas
    await pyodide.loadPackage(["pandas"]);

    // import pandas.. It takes times
    pyodide.runPython(`import pandas as pd `);

    console.log("Pandas loaded");

    await loadChallengeList();

    loading = false;
  }

  // Init function
  async function main() {
    console.log("Truc");
  }

  // run Code
  function runCode() {
    try {
      // Move JS code to Python
      clearConsole();
      won = false;
      score = 0;
      pyodide.globals.set("raw_input", currentChallenge.input);

      // build pre-code and post-code
      const start_code = `import js\nimport ast\ndf = pd.DataFrame(raw_input.to_py())`;
      const end_code = `df_str = df.astype(str).to_dict(orient="records")\ndf = df.to_dict(orient="records")`;
      const intro_code = `line_number=len(ast.parse("""${code}""").body)`;

      // build all code
      let all_code =
        start_code + "\n" + code + "\n" + end_code + "\n" + intro_code;

      console.debug(all_code);

      // run all_code
      pyodide.runPython(all_code);

      // get results
      let json_result = pyodide.globals.get("df");
      let json_result_str = pyodide.globals.get("df_str");
      let line_number = pyodide.globals.get("line_number");

      if (line_number == 0 || line_number > 3) score = 0;
      else score = 4 - line_number;

      console.debug("LINE NUMBER", line_number);

      computed_input = json_result.toJs({ dict_converter: Object.fromEntries });
      computed_input_str = json_result_str.toJs({
        dict_converter: Object.fromEntries,
      });

      // check victories
      checkVictory();
    } catch (err) {
      let message = (err as Error).message;
      console.debug(message);
      appendConsole(message);
    }
  }

  // Next Level
  function nextLevel() {
    if (challengeListIndex < challengeList.length - 1) {
      challengeListIndex = challengeListIndex + 1;
      loadChallenge(challengeListIndex);
    }
  }

  // Previous level
  function previousLevel() {
    if (challengeListIndex > 0) {
      challengeListIndex = challengeListIndex - 1;
      loadChallenge(challengeListIndex);
    }
  }

  // Check victory
  function checkVictory() {
    console.debug("COMPUTED ", JSON.stringify(computed_input));
    console.debug("EXPECTED ", JSON.stringify(currentChallenge.expected));

    if (
      JSON.stringify(computed_input) ==
      JSON.stringify(currentChallenge.expected)
    ) {
      console.debug("WIN !!!!!!!!!!");

      localStorage.setItem(current_file, "true");

      won = true;
    }
  }
</script>

<svelte:head>
  <script
    src="https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide.js"
    on:load={loadPython}
  ></script>
</svelte:head>

<div class="drawer drawer-end">
  <input id="my-drawer-4" type="checkbox" class="drawer-toggle" />
  <div class="drawer-content ">
    <!-- Page content here -->

    <Header
      on:left={previousLevel}
      on:right={nextLevel}
      title={current_title}
      level={current_level}
      {loading}
    >
      <label
        for="my-drawer-4"
        class="drawer-button btn btn-primary text-black btn-outline font-medium gap-2"
      >
        Challenge {challengeListIndex + 1}
      </label>
    </Header>

    <Loading {loading} />

    <YouWin show={won} {score} on:next={nextLevel} />

    <Grid>
      <CodeEditor slot="a" on:run={runCode} bind:code />
      <Console bind:code={consoleOutput} slot="b" />
      <DataFrame title="Input Data" slot="c" data={computed_input_str} />
      <DataFrame
        title="Expected Data"
        slot="d"
        data={currentChallenge?.expected}
      />
    </Grid>

    <div class="flex flex-row-reverse ">
      <p class=" text-xs px-4 text-neutral-content">
        @dridk & @SteampunkIsland
      </p>
    </div>
  </div>

  <ChallengeList
    bind:current_index={challengeListIndex}
    challenges={challengeList}
  />
</div>

<style>
</style>
